import type { INodeProperties } from 'n8n-workflow';

const listOptions: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: { show: { returnAll: [false] } },
	},
];

export const spectrumProperties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'Billing', value: 'billing', description: 'Subscription and billing status' },
			{ name: 'iMessage', value: 'imessage', description: 'IMessage platform configuration and tokens' },
			{ name: 'Line', value: 'line', description: 'Dedicated iMessage lines' },
			{ name: 'Platform', value: 'platform', description: 'Enable or disable messaging platforms' },
			{ name: 'Project', value: 'project', description: 'Project details' },
			{ name: 'Slack', value: 'slack', description: 'Slack app configuration and tokens' },
			{ name: 'User', value: 'user', description: 'Project users and phone assignments' },
			{ name: 'Voice', value: 'voice', description: 'Voice platform and SIP configuration' },
			{ name: 'Webhook', value: 'webhook', description: 'Webhook registration for inbound events' },
			{
				name: 'WhatsApp Business',
				value: 'whatsappBusiness',
				description: 'WhatsApp Business accounts, templates, and tokens',
			},
		],
		default: 'platform',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['project'] } },
		options: [
			{
				name: 'Get Project',
				value: 'getProject',
				action: 'Get project',
				description: 'Get project details',
			},
		],
		default: 'getProject',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['billing'] } },
		options: [
			{
				name: 'Get Billing Status',
				value: 'getBillingStatus',
				action: 'Get billing status',
				description: 'Get billing sync status',
			},
			{
				name: 'Get Subscription',
				value: 'getSubscription',
				action: 'Get subscription',
				description: 'Get subscription status and tier',
			},
		],
		default: 'getSubscription',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['platform'] } },
		options: [
			{
				name: 'Get Platforms',
				value: 'getPlatforms',
				action: 'Get platforms',
				description: 'List enabled messaging platforms',
			},
			{
				name: 'Toggle Platform',
				value: 'togglePlatform',
				action: 'Toggle platform',
				description: 'Enable or disable a messaging platform',
			},
			{
				name: 'Update Platform Metadata',
				value: 'updatePlatformMetadata',
				action: 'Update platform metadata',
				description: 'Update platform-specific configuration',
			},
		],
		default: 'getPlatforms',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['imessage'] } },
		options: [
			{
				name: 'Get iMessage Info',
				value: 'getImessageInfo',
				action: 'Get i message info',
				description: 'Get iMessage deployment type',
			},
			{
				name: 'Issue iMessage Tokens',
				value: 'issueImessageTokens',
				action: 'Issue i message tokens',
				description: 'Issue iMessage access tokens',
			},
		],
		default: 'getImessageInfo',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['line'] } },
		options: [
			{
				name: 'Add Line',
				value: 'addLine',
				action: 'Add line',
				description: 'Add a dedicated iMessage line',
			},
			{
				name: 'List Lines',
				value: 'listLines',
				action: 'List lines',
				description: 'List project lines',
			},
			{
				name: 'Remove Line',
				value: 'removeLine',
				action: 'Remove line',
				description: 'Remove a dedicated iMessage line',
			},
		],
		default: 'listLines',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['user'] } },
		options: [
			{
				name: 'Create User',
				value: 'createUser',
				action: 'Create user',
				description: 'Create a project user',
			},
			{
				name: 'Delete User',
				value: 'deleteUser',
				action: 'Delete user',
				description: 'Delete a project user',
			},
			{
				name: 'Get User',
				value: 'getUser',
				action: 'Get user',
				description: 'Get a project user by ID',
			},
			{
				name: 'List Users',
				value: 'listUsers',
				action: 'List users',
				description: 'List project users',
			},
		],
		default: 'listUsers',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['webhook'] } },
		options: [
			{
				name: 'Delete Webhook',
				value: 'deleteWebhook',
				action: 'Delete webhook',
				description: 'Delete a registered webhook',
			},
			{
				name: 'List Webhooks',
				value: 'listWebhooks',
				action: 'List webhooks',
				description: 'List registered webhooks',
			},
			{
				name: 'Register Webhook',
				value: 'registerWebhook',
				action: 'Register webhook',
				description: 'Register a webhook URL for inbound events',
			},
		],
		default: 'listWebhooks',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['slack'] } },
		options: [
			{
				name: 'Delete Installation',
				value: 'deleteInstallation',
				action: 'Delete installation',
				description: 'Delete a Slack workspace installation',
			},
			{
				name: 'Delete Slack Config',
				value: 'deleteSlackConfig',
				action: 'Delete slack config',
				description: 'Delete Slack app configuration',
			},
			{
				name: 'Get Slack Config',
				value: 'getSlackConfig',
				action: 'Get slack config',
				description: 'Get Slack app configuration',
			},
			{
				name: 'Issue Slack Tokens',
				value: 'issueSlackTokens',
				action: 'Issue slack tokens',
				description: 'Issue Slack access tokens',
			},
			{
				name: 'List Installations',
				value: 'listInstallations',
				action: 'List installations',
				description: 'List Slack workspace installations',
			},
			{
				name: 'Set Up Slack',
				value: 'setupSlack',
				action: 'Set up slack',
				description: 'Set up a Slack app via workspace-admin tokens',
			},
			{
				name: 'Upsert Installation',
				value: 'upsertInstallation',
				action: 'Upsert installation',
				description: 'Create or update a Slack workspace installation',
			},
			{
				name: 'Upsert Slack Config',
				value: 'upsertSlackConfig',
				action: 'Upsert slack config',
				description: 'Create or update Slack app configuration',
			},
		],
		default: 'getSlackConfig',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['whatsappBusiness'] } },
		options: [
			{
				name: 'Create Template',
				value: 'createTemplate',
				action: 'Create template',
				description: 'Create a WhatsApp message template',
			},
			{
				name: 'Delete Template',
				value: 'deleteTemplate',
				action: 'Delete template',
				description: 'Delete a WhatsApp message template',
			},
			{
				name: 'Issue WhatsApp Tokens',
				value: 'issueWhatsappTokens',
				action: 'Issue whats app tokens',
				description: 'Issue WhatsApp Business access tokens',
			},
			{
				name: 'List Accounts',
				value: 'listAccounts',
				action: 'List accounts',
				description: 'List WhatsApp Business accounts',
			},
			{
				name: 'List Templates',
				value: 'listTemplates',
				action: 'List templates',
				description: 'List WhatsApp message templates',
			},
			{
				name: 'Update Template',
				value: 'updateTemplate',
				action: 'Update template',
				description: 'Update a WhatsApp message template',
			},
		],
		default: 'listAccounts',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['voice'] } },
		options: [
			{
				name: 'Delete SIP Inbound',
				value: 'deleteSipInbound',
				action: 'Delete SIP inbound',
				description: 'Delete SIP inbound configuration',
			},
			{
				name: 'Get SIP Inbound',
				value: 'getSipInbound',
				action: 'Get SIP inbound',
				description: 'Get SIP inbound configuration',
			},
			{
				name: 'Issue Voice Tokens',
				value: 'issueVoiceTokens',
				action: 'Issue voice tokens',
				description: 'Issue voice access tokens',
			},
			{
				name: 'Update SIP Inbound',
				value: 'updateSipInbound',
				action: 'Update SIP inbound',
				description: 'Set or update SIP inbound configuration',
			},
		],
		default: 'getSipInbound',
	},
	{
		displayName: 'Platform Name or ID',
		name: 'platform',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getPlatformOptions' },
		required: true,
		default: 'imessage',
		description: 'The messaging platform to configure. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['platform'], operation: ['togglePlatform', 'updatePlatformMetadata'] } },
	},
	{
		displayName: 'Enabled',
		name: 'enabled',
		type: 'boolean',
		required: true,
		default: true,
		description: 'Whether the platform should be enabled or disabled',
		displayOptions: { show: { resource: ['platform'], operation: ['togglePlatform'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['platform'], operation: ['updatePlatformMetadata'], platform: ['imessage'] },
		},
		options: [
			{
				displayName: 'iMessage Enabled',
				name: 'imessageEnabled',
				type: 'boolean',
				default: true,
				description: 'Whether iMessage is enabled for this platform metadata update',
			},
		],
	},
	{
		displayName: 'Platform',
		name: 'linePlatform',
		type: 'options',
		options: [{ name: 'iMessage', value: 'imessage' }],
		default: 'imessage',
		description: 'Filter lines by platform',
		displayOptions: { show: { resource: ['line'], operation: ['listLines'] } },
	},
	...withListDisplayOptions(['line'], ['listLines']),
	{
		displayName: 'Line Name or ID',
		name: 'lineId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getLineOptions' },
		required: true,
		default: '',
		description: 'The dedicated line to remove. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['line'], operation: ['removeLine'] } },
	},
	{
		displayName: 'User Type',
		name: 'userType',
		type: 'options',
		required: true,
		options: [
			{ name: 'Dedicated', value: 'dedicated' },
			{ name: 'Shared', value: 'shared' },
		],
		default: 'shared',
		displayOptions: { show: { resource: ['user'], operation: ['createUser'] } },
	},
	{
		displayName: 'Phone Number',
		name: 'phoneNumber',
		type: 'string',
		required: true,
		default: '',
		placeholder: '+15551234567',
		description: 'E.164 phone number for the user',
		displayOptions: { show: { resource: ['user'], operation: ['createUser'] } },
	},
	{
		displayName: 'Assigned Phone Number',
		name: 'assignedPhoneNumber',
		type: 'string',
		required: true,
		default: '',
		placeholder: '+15551234567',
		description: 'Dedicated line phone number assigned to the user',
		displayOptions: {
			show: { resource: ['user'], operation: ['createUser'], userType: ['dedicated'] },
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'userAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['user'], operation: ['createUser'] } },
		options: [
			{ displayName: 'Email', name: 'email', type: 'string', placeholder: 'name@email.com', default: '' },
			{ displayName: 'First Name', name: 'firstName', type: 'string', default: '' },
			{ displayName: 'Last Name', name: 'lastName', type: 'string', default: '' },
		],
	},
	{
		displayName: 'User Type',
		name: 'userTypeFilter',
		type: 'options',
		options: [
			{ name: 'All', value: '' },
			{ name: 'Dedicated', value: 'dedicated' },
			{ name: 'Shared', value: 'shared' },
		],
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['listUsers'] } },
	},
	{
		displayName: 'User ID',
		name: 'userIdFilter',
		type: 'string',
		default: '',
		description: 'Filter by user ID',
		displayOptions: { show: { resource: ['user'], operation: ['listUsers'] } },
	},
	...withListDisplayOptions(['user'], ['listUsers']),
	{
		displayName: 'User Name or ID',
		name: 'userId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getUserOptions' },
		required: true,
		default: '',
		description: 'The project user to load or delete. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['user'], operation: ['getUser', 'deleteUser'] } },
	},
	...withListDisplayOptions(['webhook'], ['listWebhooks']),
	{
		displayName: 'Webhook URL',
		name: 'webhookUrl',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://your-n8n.example.com/webhook/...',
		description: 'The URL that will receive Spectrum webhook events',
		displayOptions: { show: { resource: ['webhook'], operation: ['registerWebhook'] } },
	},
	{
		displayName: 'Webhook Name or ID',
		name: 'webhookId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getWebhookOptions' },
		required: true,
		default: '',
		description: 'The registered webhook to delete. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['webhook'], operation: ['deleteWebhook'] } },
	},
	...withListDisplayOptions(['slack'], ['listInstallations']),
	{
		displayName: 'Additional Fields',
		name: 'slackConfigFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['slack'], operation: ['upsertSlackConfig'] } },
		options: [
			{
				displayName: 'App ID',
				name: 'appId',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Client ID',
				name: 'clientId',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Client Secret',
				name: 'clientSecret',
				type: 'string',
				typeOptions: { password: true },
				default: '',
			},
			{
				displayName: 'Enabled Features',
				name: 'enabledFeatures',
				type: 'string',
				default: '',
				description: 'Comma-separated list of enabled Slack features',
			},
			{
				displayName: 'Signing Secret',
				name: 'signingSecret',
				type: 'string',
				typeOptions: { password: true },
				default: '',
			},
		],
	},
	{
		displayName: 'App Name',
		name: 'appName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['slack'], operation: ['setupSlack'] } },
	},
	{
		displayName: 'Enabled Features',
		name: 'enabledFeatures',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of enabled Slack features',
		displayOptions: { show: { resource: ['slack'], operation: ['setupSlack'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'slackSetupAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['slack'], operation: ['setupSlack'] } },
		options: [
			{
				displayName: 'Config Token',
				name: 'configToken',
				type: 'string',
				typeOptions: { password: true },
				default: '',
			},
			{
				displayName: 'Refresh Token',
				name: 'refreshToken',
				type: 'string',
				typeOptions: { password: true },
				default: '',
			},
		],
	},
	{
		displayName: 'Team ID',
		name: 'teamId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'T01234567',
		description: 'Slack workspace team ID for the installation',
		displayOptions: { show: { resource: ['slack'], operation: ['upsertInstallation'] } },
	},
	{
		displayName: 'Team Name or ID',
		name: 'installationTeamId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getSlackTeamOptions' },
		required: true,
		default: '',
		description: 'The Slack workspace installation to delete. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['slack'], operation: ['deleteInstallation'] } },
	},
	{
		displayName: 'Team Name',
		name: 'teamName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['slack'], operation: ['upsertInstallation'] } },
	},
	{
		displayName: 'App ID',
		name: 'appId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['slack'], operation: ['upsertInstallation'] } },
	},
	{
		displayName: 'Bot Token',
		name: 'botToken',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: { show: { resource: ['slack'], operation: ['upsertInstallation'] } },
	},
	{
		displayName: 'Bot User ID',
		name: 'botUserId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['slack'], operation: ['upsertInstallation'] } },
	},
	{
		displayName: 'Granted Scopes',
		name: 'grantedScopes',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated OAuth scopes granted to the bot',
		displayOptions: { show: { resource: ['slack'], operation: ['upsertInstallation'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'slackInstallationAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['slack'], operation: ['upsertInstallation'] } },
		options: [
			{
				displayName: 'Bot Refresh Token',
				name: 'botRefreshToken',
				type: 'string',
				typeOptions: { password: true },
				default: '',
			},
			{
				displayName: 'Bot Token Expires In Sec',
				name: 'botTokenExpiresInSec',
				type: 'number',
				default: 0,
			},
		],
	},
	...withListDisplayOptions(['whatsappBusiness'], ['listAccounts']),
	{
		displayName: 'Account Name or ID',
		name: 'accountId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getWhatsappAccountOptions' },
		required: true,
		default: '',
		description: 'The WhatsApp Business account to use. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: {
			show: {
				resource: ['whatsappBusiness'],
				operation: ['listTemplates', 'createTemplate', 'updateTemplate', 'deleteTemplate'],
			},
		},
	},
	...withListDisplayOptions(['whatsappBusiness'], ['listTemplates']),
	{
		displayName: 'Template Name',
		name: 'templateName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['whatsappBusiness'], operation: ['createTemplate'] } },
	},
	{
		displayName: 'Template Language',
		name: 'templateLanguage',
		type: 'string',
		required: true,
		default: 'en',
		displayOptions: { show: { resource: ['whatsappBusiness'], operation: ['createTemplate'] } },
	},
	{
		displayName: 'Template Category',
		name: 'templateCategory',
		type: 'options',
		required: true,
		options: [
			{ name: 'Authentication', value: 'AUTHENTICATION' },
			{ name: 'Marketing', value: 'MARKETING' },
			{ name: 'Utility', value: 'UTILITY' },
		],
		default: 'UTILITY',
		displayOptions: {
			show: { resource: ['whatsappBusiness'], operation: ['createTemplate', 'updateTemplate'] },
		},
	},
	{
		displayName: 'Template Components',
		name: 'templateComponents',
		type: 'json',
		required: true,
		default: '[{"type":"BODY","text":"Hello {{1}}"}]',
		description: 'JSON array of WhatsApp template components',
		displayOptions: { show: { resource: ['whatsappBusiness'], operation: ['createTemplate'] } },
	},
	{
		displayName: 'Template Components',
		name: 'templateComponents',
		type: 'json',
		default: '',
		description: 'JSON array of WhatsApp template components',
		displayOptions: { show: { resource: ['whatsappBusiness'], operation: ['updateTemplate'] } },
	},
	{
		displayName: 'Template Name or ID',
		name: 'templateId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getWhatsappTemplateOptions' },
		required: true,
		default: '',
		description: 'The WhatsApp template to update or delete. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: {
			show: { resource: ['whatsappBusiness'], operation: ['updateTemplate', 'deleteTemplate'] },
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'templateAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['whatsappBusiness'], operation: ['createTemplate', 'updateTemplate'] },
		},
		options: [
			{
				displayName: 'Allow Category Change',
				name: 'allowCategoryChange',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Category',
				name: 'category',
				type: 'options',
				options: [
					{ name: 'Authentication', value: 'AUTHENTICATION' },
					{ name: 'Marketing', value: 'MARKETING' },
					{ name: 'Utility', value: 'UTILITY' },
				],
				default: 'UTILITY',
			},
			{
				displayName: 'Message Send TTL Seconds',
				name: 'messageSendTtlSeconds',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Parameter Format',
				name: 'parameterFormat',
				type: 'options',
				options: [
					{ name: 'Named', value: 'NAMED' },
					{ name: 'Positional', value: 'POSITIONAL' },
				],
				default: 'POSITIONAL',
			},
		],
	},
	{
		displayName: 'SIP URI',
		name: 'sipUri',
		type: 'string',
		default: '',
		placeholder: 'sip:user@example.com',
		displayOptions: { show: { resource: ['voice'], operation: ['updateSipInbound'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'sipAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['voice'], operation: ['updateSipInbound'] } },
		options: [
			{
				displayName: 'Password',
				name: 'password',
				type: 'string',
				typeOptions: { password: true },
				default: '',
			},
			{
				displayName: 'Username',
				name: 'username',
				type: 'string',
				default: '',
			},
		],
	},
];

function withListDisplayOptions(resources: string[], operations: string[]): INodeProperties[] {
	return listOptions.map((field) => ({
		...field,
		displayOptions: { show: { resource: resources, operation: operations } },
	}));
}
